# Generated by Django 5.2.17 on 2026-09-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_stop_seq',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
