# Generated by Django 5.2.17 on 2026-09-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trip_current_stop_seq_alter_trip_current_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=30)),
                ('complaint_type', models.CharField(choices=[('LATE', 'Bus Frequently Late'), ('NOT_ARRIVED', 'Bus Did Not Arrive'), ('SKIPPED_STOP', 'Bus Skipped My Stop'), ('CANCELLED', 'Bus Service Cancelled'), ('WRONG_ROUTE', 'Bus Not Following Route'), ('WRONG_LOCATION', 'Wrong GPS Location'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tracker.passenger')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='tracker.route')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='tracker.busstop')),
            ],
        ),
    ]
